WordStack.Web/Models/Sentence.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace WordStack.Web.Models
{
    public class Sentence
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }
        [JsonPropertyName("stringValue")]
        public string StringValue { get; set; }
    }
}

WordStack.Web/Models/Word.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace WordStack.Web.Models
{
    public class Word
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }
        [JsonPropertyName("stringValue")]
        public string StringValue { get; set; }

        [JsonPropertyName("wordTypeId")]
        public int WordTypeId { get; set; }
        public WordType WordType { get; set; }
    }
}

WordStack.Web/Models/WordType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace WordStack.Web.Models
{
    public class WordType
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }
        [JsonPropertyName("stringValue")]
        public string StringValue { get; set; }
    }
}

WordStack.Web/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using WordStack.Web.Models;

namespace WordStack.Web.Pages
{
    public class CreateModel : PageModel
    {
        private readonly ILogger<CreateModel> _logger;
        private readonly IWordStackClient _context;

        public SelectList WordTypeSL { get; set; }
        public SelectList WordSL { get; set; }
        [BindProperty]
        public Sentence Sentence { get; set; }

        [BindProperty]
        public Word Word { get; set; }

        [BindProperty(SupportsGet = true)]
        public int wordTypeId { get; set; }
        public int wordId { get; set; }

        public CreateModel(ILogger<CreateModel> logger, IWordStackClient context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task OnGetAsync()
        {
            await BindWordTypeDropDown();
        }

        public async Task<JsonResult> OnGetWords()
        {
            var s = new JsonResult(await _context.Words(wordTypeId));
            return new JsonResult(await _context.Words(wordTypeId));
        }

        async Task BindWordTypeDropDown()
        {
            var wordTypesQuery = await _context.WordTypes();
            WordTypeSL = new SelectList(wordTypesQuery.ToList(), "Id", "StringValue");
        }

        public async Task<IActionResult> OnPostSaveSentenceAsync()
        {
            try
            {
                await _context.AddNewSentence(Sentence);
                return RedirectToPage("./Index");
            }
            catch
            {
                await BindWordTypeDropDown();
                return Page();
            }
        }
    }
}

WordStack.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WordStack.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WordStack.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using WordStack.Web.Models;

namespace WordStack.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IWordStackClient _context;

        public IEnumerable<Sentence> Sentences { get; set; }

        public IndexModel(ILogger<IndexModel> logger, IWordStackClient context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task OnGetAsync()
        {
            Sentences = await _context.Sentences();
        }
    }
}

WordStack.Web/Pages/Create.cshtml
@page
@model WordStack.Web.Pages.CreateModel
@{
    ViewData["Title"] = "Create Sentence";
}

<h2>Create</h2>
<h4>Sentence</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div class="form-group">
                <input asp-for="Sentence.Id" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <label class="control-label">Sentence</label>
                <input asp-for="Sentence.StringValue" class="form-control" />
            </div>
            <div class="form-row">
                <div class="col">
                    <select id="WordTypeId" asp-for="Word.WordTypeId" class="form-control"
                            asp-items="@Model.WordTypeSL">
                        <option value="-1">-- Select Word Type --</option>
                    </select>
                </div>
                <div class="col">
                    <select id="WordId" asp-for="Word.StringValue" class="form-control selectpicker" data-live-search="true">
                        <option value="" data-hidden="true">-- Select Word --</option>
                    </select>
                    <input asp-for="Word.StringValue" id="WordNew" class="form-control d-none" />
                </div>
                <div class="col">
                    <input type="button" onclick="addWord();" value="Add" class="btn btn-default" />
                </div>
            </div>
            <div class="form-group">
                <input type="submit" asp-page-handler="SaveSentence" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-page="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function addWord() {
            let sentence = document.getElementById('Sentence_StringValue');
            let word = document.getElementById('WordId');

            if (sentence.value !== null && sentence.value !== '') {
                sentence.value = sentence.value.concat(" ");
            }
            
            if (!$("#WordNew").hasClass("d-none")) {
                $("#WordNew").addClass("d-none");
                sentence.value = sentence.value.concat($("#WordNew").val());
            }
            else {
                sentence.value = sentence.value.concat(word.options[word.selectedIndex].text);
            }
            $("#WordId").empty();
            $("#WordId").append("<option value='-1'>-- Select Word --</option>");
            $('.selectpicker').selectpicker('refresh');
            $("#WordTypeId").val("-1");
        }

        $(function () {
            $('.selectpicker').selectpicker({
                liveSearch: true
            });
        });

        $(function () {
            $("#WordId").on("change", function () {
                let word = document.getElementById('WordId');
                if (word.value === '0') {
                    $("#WordNew").removeClass("d-none");
                }
                else {
                    $("#WordNew").addClass("d-none");
                }
            });
        });

        $(function () {
            $("#WordTypeId").on("change", function () {
                var wordTypeId = $(this).val();
                $("#WordId").empty();
                $("#WordId").append("<option value='-1'>-- Select Word --</option>");
                $("#WordId").append("<option value='0'>Other (specify)</option>");
                $.getJSON(`?handler=Words&wordTypeId=${wordTypeId}`, (data) => {
                    $.each(data, function (i, item) {
                        $("#WordId").append(`<option value="${item.id}" data-tokens="${item.stringValue}">${item.stringValue}</option>`);
                    });
                    $('.selectpicker').selectpicker('refresh');
                });
            });
        });



    </script>
}

WordStack.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Let's build some sentences!</p>

    <hr />
    <h2>Sentences</h2>

</div>
<div>
    <p>
        <a asp-page="Create">Create New</a>
    </p>
    <table class="table">
        <tbody>
            @foreach (var item in Model.Sentences)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StringValue)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

WordStack.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WordStack.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WordStack.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WordStack.Web - <a href="https://github.com/HenkoR/WordStack.Web" target="_blank">HenkoR</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>